### ISSUE TITLE
Create Git tags for version releases

### ISSUE THREAD

**Issue by MarkMaldaba** [gabelerner/canvg#384]
Hi there,

It looks like in the move to Github, you've lost history of previous releases.

Please can you create tags in the repository that correspond to previously released versions so that downstream users can manage their version-control sensibly.

For example, I would expect to find a "1.3" tag that matches the contents of http://canvg.googlecode.com/files/canvg-1.3.zip, and similar for all other previous public releases.

Tags should be created for all previous releases, and you should continue to tag stable versions in this manner as and when they are released, so that it is easy to see when an upgrade is available and to check what has changed between versions.

Thank you.

**Comment by gabelerner** [comment]
Most of the releases on google were "beta". the 1.0 release is my new starting point for working releases so all prior should really be upgraded to this one, and going forward, i'll maintain what you are asking for.

i guess i can backfill the google ones, but i don't seem to have access to prior downloads on google code since it now redirects here.  if you have an idea of what commits went into what download, i'll create the appropriate tags.

**Comment by MarkMaldaba** [comment]
The wayback machine still has a copy of the Google site: https://web.archive.org/web/20140822111616/https://code.google.com/p/canvg/

Not everything is available, but it gives us some dates for the releases which (along with the zip contents) should help you match them to a specific revision:

* http://canvg.googlecode.com/files/canvg-1.0.zip (Jun 22, 2011)
* http://canvg.googlecode.com/files/canvg-1.1.zip (Nov 18, 2011)
* http://canvg.googlecode.com/files/canvg-1.2.zip (Jul 15, 2012)
* http://canvg.googlecode.com/files/canvg-1.3.zip (Jun 13, 2013)

There are also some older releases, from before version numbering was introduced (e.g. http://canvg.googlecode.com/files/canvg-r97.zip) but I don't think these are worth bothering with.

The main point is to provide an easy way for existing users to compare versions, and to access source code for older versions.  I strongly advise continuing the numbering from where you got to (e.g. 1.5 or 2.0) as anything else would be confusing (there is already a version 1.0 that people are using).

**Comment by MarkMaldaba** [comment]
> Most of the releases on google were "beta"

There is nothing in the Google project page, source code or versioning scheme that indicated this, and as you've already released versions 1.0 to 1.3, I would strongly suggest either continuing with 1.4 or starting afresh at 2.0.

**Comment by MikeJoyce19** [comment]
+1.

Your tag "v.1.0.0" corresponds to a commit from a while ago. I'm specifically looking for a tag related to 5585322833aa75cca2bab657b67307d708e0db95

I'm using jspm and my choices are either using master (which is currently broken due to a potential jspm issue - https://github.com/gabelerner/canvg/issues/393) or v1.0.0 which isn't working either unless i load RGBColor.js globally.

Thanks.

**Comment by gabelerner** [comment]
so i moved the current release to v1.4 and added some tags for the prior releases using the dates mentioned. does it look ok now for this issue?

**Comment by MarkMaldaba** [comment]
Thanks @gabelerner!

The tags aren't identical to the original zip files, as the original files excluded the sub-directories (as these aren't really required for general release).  I don't know how much this matters to anyone else, but it's not a big deal from my point of view.  The files that were present in the original zips are identical to what is in the new releases, which is the main thing.

Thanks for sorting this out - it is massively appreciated!!  I'm sure it will help the project moving forwards, as well as reducing confusion.
