### ISSUE TITLE
Canvg not working with safari 

### ISSUE THREAD

**Issue by manishp05** [gabelerner/canvg#399]
with canvg.js not able to generate png image from svg

**Comment by JWo1F** [comment]
The same here

**Comment by gabelerner** [comment]
what errors are there? please reopen w/ more details

**Comment by Manbec** [comment]
Hello, I was looking at the same problem and finally came to a solution by looking at your examples on http://canvg.github.io/canvg/examples/index.htm

Turns out that I was passing data like this:
<?xml version="1.0"?><svg>...</svg>

Which works fine on chrome, for example, but will not render in Safari.

You need to pass the svg data as in the examples:
<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:se="http://svg-edit.googlecode.com" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200">...</svg>

I suppose these fields are necessary for different readers or browsers to be able to process the svg.

Hope it helps someone else.
